### Softmax function
$$\frac{e^{p_i}}{\sum_i e^{p_i}}$$

### Cross entropy function
$$-\sum_c \text{Ob}_c \ln \text{Pr}_c 

### Minus -ln [0,1]
<img src="minus_ln.png" alt="MarineGEO circle logo" style="height: 400px; width:400px;"/>

In [3]:
import torch
torch.manual_seed(1337)
B,T,C = 2,4,2
x = torch.randn(B,T,C)
print(x)

tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643]],

        [[ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]]])


In [6]:
xbow = torch.zeros(B,T,C)
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev,0)
print(xbow) 

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238]],

        [[ 0.3612,  1.1679],
         [-0.4944,  0.3289],
         [-0.2509,  0.1393],
         [-0.4185,  0.4903]]])


In [14]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
print(a)
rowsums = torch.sum(a, 1, keepdim=True)
a = a / rowsums
print(a)   
b = torch.randint(0,10,(3,2)).float()
print(b)
c = a @ b
print(c)

 

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [8]:
row_sums = torch.sum(a, dim=1)  # Calculate the sum of each row
print(row_sums)
# Divide each row by its summation
result = a / row_sums.view(-1, 1)

print(result)

tensor([1., 1., 1.])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])


In [12]:
import torch
import torch.nn as nn

# Define input and output dimensions
input_dim = 10
output_dim = 50

# Create an instance of nn.Linear
linear_layer = nn.Linear(input_dim, output_dim)

# Example input data
input_data = torch.randn(input_dim)  # Assuming a batch size of 32

# Pass the input data through the linear layer
output = linear_layer(input_data)
print(input_data)
print(output)

tensor([ 0.0096, -1.0961, -0.6700, -0.1880, -0.9494,  0.0321,  0.2431, -0.5684,
        -0.2799,  1.1602])
tensor([-0.0985, -0.7441, -0.1653, -0.2658,  0.6157,  0.2532, -0.1613,  0.3949,
         0.4059, -0.3236,  0.6973,  0.1065,  0.9914, -0.0178, -0.5851, -0.3494,
        -0.6643, -0.2646,  0.1990, -0.0850, -0.0412, -0.7607,  0.7153, -0.1720,
         0.5302, -0.2223,  0.4829, -0.0497, -0.5736,  0.0923, -0.9671, -0.0611,
        -0.6345,  0.5670,  0.3996, -0.1787,  0.3540, -0.0903,  0.6066, -0.6204,
         0.0192, -0.0789, -0.0211, -0.8041, -0.5403,  0.1857, -0.0247,  0.5040,
        -0.8992, -0.8430], grad_fn=<AddBackward0>)


In [23]:
import torch
import torch.nn as nn

# Define vocabulary size and embedding dimension
vocabulary_size = 10000
embedding_dim = 30

# Create an instance of nn.Embedding
embedding_layer = nn.Embedding(vocabulary_size, embedding_dim)

# Example input indices
input_indices = torch.LongTensor([5])
print(input_indices)
# Pass the input indices through the embedding layer
embedded_output = embedding_layer(input_indices)

print(embedded_output)

tensor([5])
tensor([[-1.0473,  1.2665, -0.3834, -0.5722,  0.3036,  0.6631, -0.9857, -0.4126,
          1.9631,  0.4648,  0.0355, -0.3117, -0.6701, -0.7294,  0.0769, -0.8528,
          0.4954,  0.0936, -0.2150, -0.6704, -0.6205,  0.8353, -0.3811,  0.5014,
          0.3124,  0.4451,  0.0896,  0.2643,  1.1769,  0.3203]],
       grad_fn=<EmbeddingBackward0>)


In [2]:
class Vector():
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Vector(x, y)

    def __repr__(self):
        return f'Vector({self.x}, {self.y})'
    
    def asd(self):
        self.df=3

a = Vector(1, 2)
a.foo = lambda x: x + 1
foo_prev = a.foo
a.foo = lambda x: 2 * foo_prev(x)

print(a.foo(2))
# delete a.foo
#del a.foo
#a.asd()
#print(a.df)




6


In [4]:
import torch

a = torch.arange(2,10,2)
print(a)

tensor([2, 4, 6, 8])
