### Softmax function
$$\frac{e^{p_i}}{\sum_i e^{p_i}}$$

### Cross entropy function
$$-\sum_c \text{Ob}_c \ln \text{Pr}_c 

### Minus -ln [0,1]
<img src="minus_ln.png" alt="MarineGEO circle logo" style="height: 400px; width:400px;"/>

In [3]:
import torch
torch.manual_seed(1337)
B,T,C = 2,4,2
x = torch.randn(B,T,C)
print(x)

tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643]],

        [[ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]]])


In [6]:
xbow = torch.zeros(B,T,C)
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev,0)
print(xbow) 

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238]],

        [[ 0.3612,  1.1679],
         [-0.4944,  0.3289],
         [-0.2509,  0.1393],
         [-0.4185,  0.4903]]])


In [14]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
print(a)
rowsums = torch.sum(a, 1, keepdim=True)
a = a / rowsums
print(a)   
b = torch.randint(0,10,(3,2)).float()
print(b)
c = a @ b
print(c)

 

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [8]:
row_sums = torch.sum(a, dim=1)  # Calculate the sum of each row
print(row_sums)
# Divide each row by its summation
result = a / row_sums.view(-1, 1)

print(result)

tensor([1., 1., 1.])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
